name: 'Infra-CMS'

on:
  push:
    branches:
    - test
    
jobs:
  okd-k8s:
    name: OpenShift Cluster
    runs-on: ubuntu-latest
    environment: test
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
      AWS_REGION: 'us-east-1'
      

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.2
        with:
          oc version: 'v3.11.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cluster Status
        run: oc cluster status  
